**<b><center>NUMPY</center></b>**

&nbsp; &nbsp; &nbsp; &nbsp;Dizi ve matrisler üzerinde, üst düzey matematiksel işlemler yapmamızı sağlar. Veri türü ndarray dir. Tek boyutlu olabileceği gibi, çok boyutlu da olabilir. Dizileri oluştururken türünü (int, float) belirlenebilir. <br/>

*<i><b>Tek Boyutlu Dizi (Vektör) Oluşturma</b></i><br/>*
&nbsp; &nbsp; &nbsp; &nbsp; Tek boyutlu Numpy dizisi oluşturmak için <b>np.array()</b> metodunu kullanırız.

In [1]:
import numpy as np
vektor = np.array([1,2,3,4])
print("Vektor :", vektor)
print("Boyutu :", vektor.size)
print("Veri Tipi: ", type(vektor))
print("Array Nesne Tipi : ", vektor.dtype)

Vektor : [1 2 3 4]
Boyutu : 4
Veri Tipi:  <class 'numpy.ndarray'>
Array Nesne Tipi :  int32


&nbsp; &nbsp; &nbsp; &nbsp;Dizi elemanlarına erişebilir, değişiklik yapabiliriz.

In [2]:
print("vektor[3] :",vektor[3])
vektor[0] = 5
print("vektor[0] :",vektor[0])
print("Vektor :", vektor)

vektor[3] : 4
vektor[0] : 5
Vektor : [5 2 3 4]


*<i><b>İki Boyutlu Dizi Oluşturma</b></i><br/>*
&nbsp; &nbsp; &nbsp; &nbsp; İki boyutlu dizileri de <b>np.array()</b> metodu ile oluştururuz.

In [3]:
#2 boyutlu dizi oluşturma
iki_boyutlu = np.array([[1.2,1.3,3.4],[2.5,6,5.5]])
print("Dizi \n", iki_boyutlu)
print("Boyutu :", iki_boyutlu.size)
print("Veri Tipi : ", type(iki_boyutlu))
print("Array Nesne Tipi : ", iki_boyutlu.dtype)
print("Dizinin Boyutu   : ", iki_boyutlu.shape)
print("iki_boyutlu[0,2] :", iki_boyutlu[0,2])


Dizi 
 [[1.2 1.3 3.4]
 [2.5 6.  5.5]]
Boyutu : 6
Veri Tipi :  <class 'numpy.ndarray'>
Array Nesne Tipi :  float64
Dizinin Boyutu   :  (2, 3)
iki_boyutlu[0,2] : 3.4


*<i><b>Özel Numpy Dizileri</b></i><br/>*
<br>
&nbsp; &nbsp; &nbsp; &nbsp;<b>np.arange()</b> başlangıç, bitiş ve sayıların tipini belirleyebileceğimiz, artan sayılardan oluşan bir dizi oluşturur.

In [4]:
artan_matris = np.arange(1,10,dtype=float)
print(artan_matris)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


&nbsp; &nbsp; &nbsp; &nbsp;<b>np.linspace()</b> belirlediğimiz başlangıç ve bitiş aralığında eşit olacak şekilde dilimler oluşturur. Dilim miktarı en fazla 50'dir.

In [5]:
dilim_matris = np.linspace(0,50,5)
print(dilim_matris)

[ 0.  12.5 25.  37.5 50. ]


*<i><b>Özel Numpy Matrisleri</b></i><br/>*
<br>
&nbsp; &nbsp; &nbsp; &nbsp;<b>np.zeros()</b> tamamı 0 sayısından oluşan bir matris oluşturur.

In [6]:
sifir_matris = np.zeros((2,2))
print(sifir_matris)

[[0. 0.]
 [0. 0.]]


&nbsp; &nbsp; &nbsp; &nbsp;<b>np.ones()</b> tamamı 1 sayısından oluşan bir matris oluşturur.

In [7]:
bir_matris = np.ones((3,2))
print(bir_matris)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


&nbsp; &nbsp; &nbsp; &nbsp;<b>np.full()</b> sabit matristir. Belirleyeceğimiz değer ile, istediğimiz boyutta matris oluşturur.

In [8]:
sabit_matris = np.full((2,2),7)
print(sabit_matris)

[[7 7]
 [7 7]]


&nbsp; &nbsp; &nbsp; &nbsp;<b>np.eye()</b> belirlediğimiz boyutta birim matris oluşturmamızı sağlar.

In [8]:
birim_matris = np.eye(2)
print(birim_matris)

[[1. 0.]
 [0. 1.]]


&nbsp; &nbsp; &nbsp; &nbsp;<b>np.random()</b> istediğimiz boyutta değerleri 0-1 arasında olacak şekilde rastgele değerlerden oluşan bir matris oluşturmamızı sağlar.

In [9]:
rastgele_matris = np.random.random((2,2))
print(rastgele_matris)

[[0.43264606 0.05510894]
 [0.34511772 0.47597606]]


*<i><b>Özel Numpy Dizileri</b></i><br/>*
&nbsp; &nbsp; &nbsp; &nbsp;Matrisleri istediğimiz şekilde bölümleyerek yeni değerler atayabiliriz. Birbiri ile bağlantılı matrislerde, ilkinde yapacağımız değişikliğin diğerlerini de etkileyeceğini unutmayın.<br/>
<br>
&nbsp; &nbsp; &nbsp; &nbsp;<b>Tek Boyutta Dilimleme</b>

In [10]:
dizi = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(dizi)
print("dizi[1,:] : ", dizi[1,:])
print("dizi[:,2] : ",dizi[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dizi[1,:] :  [4 5 6]
dizi[:,2] :  [3 6 9]


&nbsp; &nbsp; &nbsp; &nbsp;<b>İki Boyutta Dilimlenme</b>

In [11]:
print("dizi[:2, 1:2] : \n",dizi[:2, 1:2])

dizi[:2, 1:2] : 
 [[2]
 [5]]


*<i><b>Matris Fonksiyonları</b></i><br/>*
<br>
&nbsp; &nbsp; &nbsp; &nbsp;<b>Sum</b> bütün elemanların toplamını verir. <b>axis</b> parametresinde yapacağımız değişiklik ile satır ya da sütun toplamını da alabiliriz.

In [12]:
x = np.array([[1,2,3],[4,5,6]])
print("Matris :\n", x)
print("Matris Toplamı : ", np.sum(x))
print("Axis = 0 " , np.sum(x, axis=0))
print("Axis = 1 " , np.sum(x, axis=1))

Matris :
 [[1 2 3]
 [4 5 6]]
Matris Toplamı :  21
Axis = 0  [5 7 9]
Axis = 1  [ 6 15]


&nbsp; &nbsp; &nbsp; &nbsp;<b>Mean</b> elemanların ortalamasını verir.

In [13]:
print("Matrisin Ortalaması : ", np.mean(x))
print("Axis = 0 " , np.mean(x, axis=0))
print("Axis = 1 " , np.mean(x, axis=1))

Matrisin Ortalaması :  3.5
Axis = 0  [2.5 3.5 4.5]
Axis = 1  [2. 5.]


&nbsp; &nbsp; &nbsp; &nbsp;<b>Transpose</b> satır ve sütunların yerlerini değiştirir. Vektörlerin devriği alınmaz.

In [14]:
transpose = np.array([[1,2], [3,4]])
print("Matris  \n", transpose)
print("\nTranspose Alınınca  \n", (transpose.T))

Matris  
 [[1 2]
 [3 4]]

Transpose Alınınca  
 [[1 3]
 [2 4]]


&nbsp; &nbsp; &nbsp; &nbsp;<b>Reshape</b> matrisin boyutunu değiştirmemizi sağlar. İşlem sırasında matris boyutunun değişiklik için uygun olması gerekmektedir.

In [15]:
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Matris \n", dizi)
print("\nBoyut Değişimi \n", dizi.reshape(2,3,2))

Matris 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Boyut Değişimi 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


<b>İletişim</b> <br/>
<ul><a href="https://linkedin.com/in/berkayyurur" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="berkayyurur" height="15" width="20" /></a></ul>