In [ ]:
### NUMPY

In [1]:
#Tek boyutlu Numpy dizisi
import numpy as np
vektor = np.array([1,2,3,4])
print("Vektor :", vektor)
print("Boyutu :", vektor.size)
print("Veri Tipi: ", type(vektor))
print("Array Nesne Tipi : ", vektor.dtype)

Vektor : [1 2 3 4]
Boyutu : 4
Veri Tipi:  <class 'numpy.ndarray'>
Array Nesne Tipi :  int32


In [2]:
#Dizinin Elemanlarına Erişim
print("vektor[3] :",vektor[3])
vektor[0] = 5
print("vektor[0] :",vektor[0])
print("Vektor :", vektor)


vektor[3] : 4
vektor[0] : 5
Vektor : [5 2 3 4]


In [3]:
#2 boyutlu dizi oluşturma
iki_boyutlu = np.array([[1.2,1.3,3.4],[2.5,6,5.5]])
print("Dizi \n", iki_boyutlu)
print("Boyutu :", iki_boyutlu.size)
print("Veri Tipi : ", type(iki_boyutlu))
print("Array Nesne Tipi : ", iki_boyutlu.dtype)
print("Dizinin Boyutu   : ", iki_boyutlu.shape)
print("iki_boyutlu[0,2] :", iki_boyutlu[0,2])


Dizi 
 [[1.2 1.3 3.4]
 [2.5 6.  5.5]]
Boyutu : 6
Veri Tipi :  <class 'numpy.ndarray'>
Array Nesne Tipi :  float64
Dizinin Boyutu   :  (2, 3)
iki_boyutlu[0,2] : 3.4


In [4]:
#np.arange( )
artan_matris = np.arange(1,10,dtype=float)
print(artan_matris)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
#np.linspace( )
dilim_matris = np.linspace(0,50,5)
print(dilim_matris)

[ 0.  12.5 25.  37.5 50. ]


In [6]:
#np.zeros( )
sifir_matris = np.zeros((2,2))
print(sifir_matris)

[[0. 0.]
 [0. 0.]]


In [7]:
#np.ones( )
bir_matris = np.ones((3,2))
print(bir_matris)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
#np.full( )
sabit_matris = np.full((2,2),7)
print(sabit_matris)

[[7 7]
 [7 7]]


In [9]:
#np.eye( )
birim_matris = np.eye(2)
print(birim_matris)

[[1. 0.]
 [0. 1.]]


In [10]:
#np.random( )
rastgele_matris = np.random.random((2,2))
print(rastgele_matris)

[[0.93721802 0.70086214]
 [0.6243496  0.79268742]]


In [11]:
#Numpy Dizilerinde Dilimlenme
dizi = np.array([[1,2,3], [4,5,6], [7,8,9]])
#Tek Boyutta Dilimlenme
print(dizi)
print("dizi[1,:] : ", dizi[1,:])
print("dizi[:,2] : ",dizi[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dizi[1,:] :  [4 5 6]
dizi[:,2] :  [3 6 9]


In [12]:
#İki Boyutta Dilimlenme
print("dizi[:2, 1:2] : \n",dizi[:2, 1:2])

dizi[:2, 1:2] : 
 [[2]
 [5]]


In [13]:
#Matris Fonksiyonları

#Sum (elemanlar toplamı)
x = np.array([[1,2,3],[4,5,6]])
print("Matris :\n", x)
print("Matris Toplamı : ", np.sum(x))
print("Axis = 0 " , np.sum(x, axis=0))
print("Axis = 1 " , np.sum(x, axis=1))

Matris :
 [[1 2 3]
 [4 5 6]]
Matris Toplamı :  21
Axis = 0  [5 7 9]
Axis = 1  [ 6 15]


In [14]:
#Mean (elemanlar ortalaması)

print("Matrisin Ortalaması : ", np.mean(x))
print("Axis = 0 " , np.mean(x, axis=0))
print("Axis = 1 " , np.mean(x, axis=1))

Matrisin Ortalaması :  3.5
Axis = 0  [2.5 3.5 4.5]
Axis = 1  [2. 5.]


In [15]:
# Transpose (matris devriği)
transpose = np.array([[1,2], [3,4]])
print("Matris  \n", transpose)
print("\nTranspose Alınınca  \n", (transpose.T))

Matris  
 [[1 2]
 [3 4]]

Transpose Alınınca  
 [[1 3]
 [2 4]]


In [16]:
#Reshape
dizi = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Matris \n", dizi)
print("\nBoyut Değişimi \n", dizi.reshape(2,3,2))

Matris 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Boyut Değişimi 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
